title: Mia Hoffman
descrition: 
url: "https://miahoffmannd.github.io"
baseurl: 

twitter: miahoffmannd
linkedin: miahoffmannd

markdown: kramdown

footer: no
footer_url: "https://github.com/miahoffmannd"
footer_text: "Page design by Mia Hoffman"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "CV"
   link: "pdfs/Hoffman_Mia_CV.pdf"
 - name: "Projects"
   link: "projects"
 - name: "News"
   link: "news"
 - name: "Resources"
   link: "resources"
 - name: "For Fun"
   link: "fun"   
 - name: "Contact Me"
   link: "contact"
