# Basic options

title: Mia Hoffman
description: "NSF GRFP PhD Student"
email: miahoff@uw.edu
twitter_username: miahoffmannd
github_username: miahoffmannd

# Site settings
theme: jekyll-theme-minimal
